# Site
name: '100sovetov'
description: 'Ответим на любые ваши вопросы и поможем советом.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
url: '//100sovetov.club'
disqus: ''
email: ''
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    admin:
      name:           Admin
      site:           
      avatar:         /assets/images/avatar1.jpg
      bio:            ""
      email:          
      twitter:        

    nickname:
      name:           Nickname
      site:           
      avatar:         /assets/images/avatar2.jpg
      bio:            ""
      email:          
      twitter:        
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: admin
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
